spring:
  datasource:
    username: root
    password: 123456-abc
    url: jdbc:mysql://47.98.143.181:33060/lygao
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.mmall.pojo

logging:
  config: classpath:logback-spring.xml
